### ISSUE TITLE
增加可以选择的加密算法

### ISSUE THREAD

**Issue by do02fw** [hwdsl2/openvpn-install#11]
**任务列表**
增加aes-128-gcm加密，这个算法速度是最快的，我尝试修改脚本中的aes256cbc为aes128gcm sha256后安装，发现安装连接后日志文件显示是aes-256-gcm-sha384，不知道为什么，明明配置文件已经显示为aes128gcm
![Screenshot_20230702_021952_OpenVPN Connect](https://github.com/hwdsl2/openvpn-install/assets/138294823/0c5d80cf-5bc4-454b-907a-1e2c67c37a00)

- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/openvpn-install/issues?q=is%3Aissue)，没有找到类似的改进建议
- [x] 这个改进建议是关于 VPN 安装脚本，而不是 OpenVPN 本身
- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/openvpn-install/blob/master/README-zh.md)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/openvpn-install/blob/master/docs/clients-zh.md)

**描述改进建议**
使用清楚简明的语言描述你的改进建议。

**你的改进建议与遇到的问题有关吗？请描述。**
（如果适用）清楚，简洁地说明问题所在。

**其它信息**
添加关于该改进建议的其它信息。

**Comment by hwdsl2** [comment]
@do02fw 你好！感谢你的建议。OpenVPN 2.4及以上的客户端会自行选择加密算法，并不一定使用服务器配置的算法。

本项目在这方面目前没有计划，但你可以参见下面另外这个项目，可能对你有用（我没有测试过它）：

https://github.com/angristan/openvpn-install#data-channel
