### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by do02fw** [hwdsl2/openvpn-install#13]
**任务列表**

- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/openvpn-install/issues?q=is%3Aissue)，没有找到类似的改进建议
- [x] 这个改进建议是关于 VPN 安装脚本，而不是 OpenVPN 本身
- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/openvpn-install/blob/master/README-zh.md)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/openvpn-install/blob/master/docs/clients-zh.md)

**描述改进建议**
使用清楚简明的语言描述你的改进建议。
1.当检测到服务器没有ipv6地址的时候自动在服务器配置文件中添加push "block-ipv6"来禁用客户端ipv6防止ipv6泄露。
2.当用户选择cloudflare DNS的时候同时添加cloudflare的IPV6 dns服务器，dhcp-option DNS 2606:4700:4700::1111和dhcp-option DNS 2606:4700:4700::1001
3.使用最新版的openvpn而不是系统软件库的openvpn，目前测试debian12最新版默认安装的openvpn版本是2.6.3，而官方已发布的版本是2.6.5，新版本更稳定安全快速，不然每次安装完还需要使用命令手动更新到openvpn官方库的最新版，
mkdir -p /etc/apt/keyrings # directory does not exist on older releases
curl -fsSL https://swupdate.openvpn.net/repos/repo-public.gpg | gpg --dearmor > /etc/apt/keyrings/openvpn-repo-public.gpg
echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/openvpn-repo-public.gpg] http://build.openvpn.net/debian/openvpn/release/2.6 bookworm main" > /etc/apt/sources.list.d/openvpn-aptrepo.list
apt update
apt upgrade

**你的改进建议与遇到的问题有关吗？请描述。**
（如果适用）清楚，简洁地说明问题所在。
我没有遇到问题
**其它信息**
添加关于该改进建议的其它信息。

**Comment by hwdsl2** [comment]
@do02fw 你好！感谢你的建议。我计划先添加第一项，对于第二项和第三项，因为脚本支持的 DNS 服务器和 Linux 发行版较多，需要考虑各种不同的情形，这些改进可以留到以后进行。
