### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by do02fw** [hwdsl2/openvpn-install#17]
**任务列表**
使用ChaCha20-Poly1305加密算法和SHA256来替代之前的加密算法，经过测试这个加密算法+UDP协议使用起来速度更快，ChaCha20-Poly1305是最快最新的算法，兼容tls1.3，aes加密算法比较老，性能差。
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/openvpn-install/issues?q=is%3Aissue)，没有找到类似的改进建议
- [x] 这个改进建议是关于 VPN 安装脚本，而不是 OpenVPN 本身
- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/openvpn-install/blob/master/README-zh.md)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/openvpn-install/blob/master/docs/clients-zh.md)

**描述改进建议**
使用清楚简明的语言描述你的改进建议。

**你的改进建议与遇到的问题有关吗？请描述。**
（如果适用）清楚，简洁地说明问题所在。

**其它信息**
添加关于该改进建议的其它信息。

**Comment by do02fw** [comment]
aes算法下载速度大约100Mbps左右，ChaCha20-Poly1305可以达到200Mbps左右，当然都开启了bbr，使用UDP协议

**Comment by do02fw** [comment]
下载很快，看视频很慢，但是wireguard就没这个问题

**Comment by do02fw** [comment]
.

**Comment by hwdsl2** [comment]
@do02fw 你好！感谢你的建议。ChaCha20-Poly1305加密算法需要OpenVPN 2.5或以上，另外某些客户端可能不支持。对于AES来说，有硬件加速的话AES-GCM的性能应该还可以。

从兼容性方面考虑，可以等以后再将本项目脚本的加密算法切换为ChaCha20-Poly1305，目前可以使用AES-GCM。
