### ISSUE TITLE
Obfuscating OpenVPN traffic

### ISSUE THREAD

**Issue by virtualos** [hwdsl2/openvpn-install#2]
Hello,

Thank you and really appreciate for such a geneious solution you share!

Is it possible to obfuscate traffic that goes through openvpn? my ISP blocked openvpn...

Thanks

**Comment by hwdsl2** [comment]
@virtualos Hello! Thank you for your kind words. This project does not support obfuscating OpenVPN traffic. You can try alternative solutions such as Shadowsocks.
