### ISSUE TITLE
增加ocserv一键安装脚本

### ISSUE THREAD

**Issue by do02fw** [hwdsl2/openvpn-install#21]
**任务列表**

- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/openvpn-install/issues?q=is%3Aissue)，没有找到类似的改进建议
- [x] 这个改进建议是关于 VPN 安装脚本，而不是 OpenVPN 本身
- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/openvpn-install/blob/master/README-zh.md)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/openvpn-install/blob/master/docs/clients-zh.md)

**描述改进建议**
使用清楚简明的语言描述你的改进建议。
运行该脚本后会检测是否安装ocserv，如果没有安装则自动安装，安装完成后再次运行可以管理用户，修改密码，添加删除用户，卸载，ocserv是一个SSL VPN协议，tcp使用了TLS1.3加密，udp使用了DTLS1.2加密，需要域名和证书，这是官网，https://ocserv.gitlab.io/www/download.html，ocserv速度很快，兼容思科的客户端anyconnect，所以也很方便。
**你的改进建议与遇到的问题有关吗？请描述。**
（如果适用）清楚，简洁地说明问题所在。

**其它信息**
添加关于该改进建议的其它信息。

**Comment by hwdsl2** [comment]
@do02fw 你好！感谢你的建议。由于ocserv超出了本项目的范围，目前本项目暂时没有计划添加ocserv的一键安装的支持。
