### ISSUE TITLE
使用竞价型云主机，每次IP

### ISSUE THREAD

**Issue by slipperstree** [hwdsl2/openvpn-install#22]
使用场景：使用竞价型云主机，每次需要的时候临时从以前安装好此shell的镜像创建一个新的实例。此时新创建的实例的IP会重新分配，我使用ios的openvpn官方App试图用之前的配置文件连接会失败（IP变化了失败是自然的）。
尝试在App中修改服务器IP，或者手动修改之前服务器上的xxx.ovpn文件中的服务器IP为当前最新的IP都无法连接。
是否不适用这种需要临时生成实例的场景？
注：每次在新的实例上重新安装是可以的。但希望直接使用以前安装好的镜像文件直接生成的实例就能用最方便了。只需要保存一个使用那个镜像的启动模板一键即可随时启动新实例并使用openvpn服务。使用完后随时销毁实例省钱。

**Comment by hwdsl2** [comment]
@slipperstree 你好！目前本项目不适用你所说的需要临时生成实例的场景。如果你的竞价型云主机支持 [startup script](https://www.vultr.com/docs/vultr-startup-scripts-quickstart-guide/) 或 [user data](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html) （示例参加链接），你可以配置每次创建云主机实例的时候运行脚本自动安装 OpenVPN。这个可能是你的用例的一个可行的方案。

**Comment by slipperstree** [comment]
非常感谢。找到了自动脚本设置的地方，现在可以实现随用随开了。

**Comment by hwdsl2** [comment]
@slipperstree 本项目新增了对使用域名（例如 vpn.example.com）作为服务器地址的支持，这对你的用例可能有帮助。你可以在新服务器上尝试一下最新版的脚本。
