### ISSUE TITLE
IPv6 only VPS: RTNETLINK answers: Network is unreachable

### ISSUE THREAD

**Issue by peterfarge** [hwdsl2/openvpn-install#23]
I'm trying to install OpenVPN Server on a IPv6 only VPS:

Starting OpenVPN setup using default options.
RTNETLINK answers: Network is unreachable
Error: Could not detect this server's IP address.
Abort. No changes were made.

**Comment by hwdsl2** [comment]
@peterfarge Hello! IPv6 only servers are not currently supported in this project. Please instead use a VPS with an IPv4 address.
