### ISSUE TITLE
The above is the warning that appears in the Openvpn-GUI software

### ISSUE THREAD

**Issue by qiaofeng568** [hwdsl2/openvpn-install#24]
Mon Jan 1 16:27:08 2024 TUN: adding address failed using service: element not found。 [status=1168 if_index=10]

Mon Jan 1 16:27:08 2024 ERROR: route addition failed using service: element not found。 [status=1168 if_index=10]
Mon Jan 1 16:27:08 2024 TUN: setting IPv6 mtu using service failed: element not found。 [status=1168 if_index=10]

Mon Jan 1 16:27:08 2024 ERROR: route addition failed using service: element not found。 [status=1168 if_index=10]
Mon Jan 1 16:27:08 2024 ERROR: route addition failed using service: element not found。 [status=1168 if_index=10]
Mon Jan 1 16:27:08 2024 ERROR: route addition failed using service: element not found。 [status=1168 if_index=10]
Mon Jan 1 16:27:08 2024 ERROR: route addition failed using service: element not found。 [status=1168 if_index=10]
Mon Jan 1 16:27:08 2024 ERROR: Some routes were not successfully added. The connection may not function correctly

The above is the warning that appears in the Openvpn-GUI software

**Comment by hwdsl2** [comment]
@qiaofeng568 Hello! Please try adding "providers legacy default" to your client's .ovpn file and import it again if necessary. For more details, see:

https://community.ipfire.org/t/tun-adding-address-failed-using-service-element-not-found/9295
