### ISSUE TITLE
mikrotik compatibility

### ISSUE THREAD

**Issue by happy-newlife** [hwdsl2/openvpn-install#25]
The script works nicely.
For connecting to it via mikrotik openvpn client we face folowing problems:

> Currently unsupported OpenVPN features:
> - UDP mode
> - LZO compression
> - TLS authentication
> - authentication without username/password

link for more info: [https://wiki.mikrotik.com/wiki/Manual:Interface/OVPN](https://wiki.mikrotik.com/wiki/Manual:Interface/OVPN)

Any idae how to adopt script to work with mikrotik?

**Comment by hwdsl2** [comment]
@happy-newlife Hello! As you've observed, this project is not currently compatible with Mikrotik as a VPN client.
