### ISSUE TITLE
Feature Request: Custom private network support

### ISSUE THREAD

**Issue by azfarhashmi** [hwdsl2/openvpn-install#26]
I deployed the openvpn on one host and its working as expected, later I installed openvon on another host and that is also working fine but the problem is I can nit use both openvpns simultaneously and seems like as they are using same private network settings which is conflicting with other setup. 

Is it possible the support custom private network during the setup so we can deploy multiple openvpn with unique private network?

**Comment by hwdsl2** [comment]
@azfarhashmi Hello! Thank you for your suggestion. Currently, there is no plan to support custom private networks, but you are welcome to customize the script to your needs, for example, edit it to change the private network before setup.
