### ISSUE TITLE
privacy matters

### ISSUE THREAD

**Issue by sec13b** [hwdsl2/openvpn-install#27]
No-logging of user activity policy.

can you add :
no logging of traffic
no logging of DNS requests
no logging of connections, including when one is made, when it disconnects, for how long, or any kind of timestamp
no logging of IP addresses
no logging of user bandwidth

verb 0
log-append /dev/null

**Comment by hwdsl2** [comment]
@sec13b Hello! The script is open source (MIT license) and you are welcome to customize it to your needs (e.g. verb 0).

By default, only basic logging is enabled (verb 3), which is helpful for troubleshooting. Most of the stuff you mentioned are not logged in the default configuration. This should work for common use cases.

For more background information, see these issues in the upstream repo:
https://github.com/Nyr/openvpn-install/issues/506
https://github.com/Nyr/openvpn-install/issues/225
