### ISSUE TITLE
TCP or UDP

### ISSUE THREAD

**Issue by sec13b** [hwdsl2/openvpn-install#28]
what is more good cryptographically secure protocol  TCP or UDP,  if i want security, privacy, and speed simultaneously.

thank  you

**Comment by hwdsl2** [comment]
@sec13b Hello! It depends on your use case. Please refer to the following links:
https://nordvpn.com/blog/tcp-or-udp-which-is-better/
https://openvpn.net/faq/what-is-tcp-meltdown/
https://openvpn.net/faq/why-does-openvpn-use-udp-and-tcp/
