### ISSUE TITLE
[QUESTION] Changing Port for Client Configuration

### ISSUE THREAD

**Issue by thesheryar** [hwdsl2/openvpn-install#29]
How can I create a new client configuration with a port 25000 or something custom? Just for one specific client.

**Comment by hwdsl2** [comment]
@thesheryar Hello! For the client configuration, edit the generated `.ovpn` file for that client, and replace the port number on this line:
```
remote <ip> <port>
```

However, on the server side, OpenVPN by default can't listen on multiple ports. You'll need to do port forwarding or run multiple OpenVPN instances to achieve that, which are outside the scope of this project.

Reference:
https://github.com/hwdsl2/openvpn-install/blob/2e0291f57390a12068147911d3fe847bceb71470/openvpn-install.sh#L848
