### ISSUE TITLE
I installed it on my Ubuntu, but it can only be used by one mobile device at a time. How can I solve this?

### ISSUE THREAD

**Issue by zhaowend** [hwdsl2/openvpn-install#30]

**Comment by hwdsl2** [comment]
@zhaowend Hello! Due to an IPsec/L2TP limitation, if you wish to connect multiple devices from behind the same NAT (e.g. home router), you must use IKEv2 or IPsec/XAuth mode. For IKEv2, create a new certificate for each new client you have. See project documentation for more details.
