### ISSUE TITLE
Ubuntu 18.04

### ISSUE THREAD

**Issue by sec13b** [hwdsl2/openvpn-install#31]
Error: Ubuntu 18.04 or higher is required to use this installer.
This version of Ubuntu is too old and unsupported.

any option to have vpn on Ubuntu 18.04

**Comment by hwdsl2** [comment]
@sec13b Hello! Ubuntu 18.04 reached EOL as of [June 2023](https://ubuntu.com//blog/18-04-end-of-standard-support). Consider using a recent Ubuntu version that is supported.
