### ISSUE TITLE
Confirmation about openvpn server type

### ISSUE THREAD

**Issue by user00036** [hwdsl2/openvpn-install#33]
CloudConnexa.
Access Server.
Community server.
OpenVPN Server built-in in a router

Which of the above is the server type?

**Comment by hwdsl2** [comment]
@user00036 Hello! This project uses the openvpn package(s) that come from your Linux distribution's repository. It is the free "community edition" as explained in [this answer](https://askubuntu.com/questions/737833/difference-between-openvpn-access-server-and-just-openvpn).

**Comment by user00036** [comment]
> @user00036你好！ 该项目使用 Linux 发行版存储库中的 openvpn 软件包。 中所解释的，它是免费的“社区版” [ 正如此答案 ](https://askubuntu.com/questions/737833/difference-between-openvpn-access-server-and-just-openvpn) 。

thanks
