### ISSUE TITLE
Does this version of openvpn support dco?

### ISSUE THREAD

**Issue by user00036** [hwdsl2/openvpn-install#35]
Both the community version and the commercial version seem to support dco. Does your deployment script enable dco by default?

**Comment by hwdsl2** [comment]
@user00036 Hello! The script does not explicitly enable or disable DCO for OpenVPN. According to the [documentation](https://community.openvpn.net/openvpn/wiki/DataChannelOffload/UsingDCO) it looks like DCO is enabled by default if it is compiled in for your Linux distribution's OpenVPN package.
