### ISSUE TITLE
小小建议

### ISSUE THREAD

**Issue by liaozan** [hwdsl2/openvpn-install#36]
感谢提供的一键安装脚本
实际使用时发现，如果在实际使用的时候需要为两个环境装openvpn（比如 develop、production）
而且两个vpn同时连接的时候，分配的ip地址段会发生冲突，都是10.8.0.0/24

可以把网段设置当成选项参数吗？可以默认为 10.8.0.0/24，如果有需求可以使用用户自定义的网段

**Comment by hwdsl2** [comment]
@liaozan 你好！感谢你的建议。目前本项目没有添加自定义网段功能的计划，你可以通过手动编辑脚本实现。
