### ISSUE TITLE
使用tls-crypt-v2加密

### ISSUE THREAD

**Issue by do02fw** [hwdsl2/openvpn-install#37]
**任务列表**

- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/openvpn-install/issues?q=is%3Aissue)，没有找到类似的改进建议
- [x] 这个改进建议是关于 VPN 安装脚本，而不是 OpenVPN 本身
- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/openvpn-install/blob/master/README-zh.md)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/openvpn-install/blob/master/docs/clients-zh.md)

**描述改进建议**
使用清楚简明的语言描述你的改进建议。
使用tls-crypt-v2加密，更安全
https://build.openvpn.net/man/openvpn-2.6/openvpn.8.html

**你的改进建议与遇到的问题有关吗？请描述。**
（如果适用）清楚，简洁地说明问题所在。

**其它信息**
添加关于该改进建议的其它信息。

**Comment by hwdsl2** [comment]
@do02fw 你好！感谢你的建议。目前本项目没有计划使用 tls-crypt 加密，但你可以手动编辑脚本在你的用例中自定义该功能。

**Comment by user00036** [comment]
> **任务列表 **
> 
> * [x]  我搜索了已有的  [Issues ](https://github.com/hwdsl2/openvpn-install/issues?q=is%3Aissue)，没有找到类似的改进建议
> * [x]  这个改进建议是关于 VPN 安装脚本，而不是 OpenVPN 本身
> * [x]  我已阅读  [自述文件 ](https://github.com/hwdsl2/openvpn-install/blob/master/README-zh.md)
> * [x]  我已按照说明  [配置 VPN 客户端 ](https://github.com/hwdsl2/openvpn-install/blob/master/docs/clients-zh.md)
> 
> **描述改进建议 ** 使用清楚简明的语言描述你的改进建议。 使用tls-crypt-v2加密，更安全 [https://build.openvpn.net/man/openvpn-2.6/openvpn.8.html ](https://build.openvpn.net/man/openvpn-2.6/openvpn.8.html)
> 
> **你的改进建议与遇到的问题有关吗？请描述。 ** （如果适用）清楚，简洁地说明问题所在。
> 
> **其它信息 ** 添加关于该改进建议的其它信息。

Doesn’t version 2.5 use tls-crypt-v2 by default?
