### ISSUE TITLE
bash openvpn.sh cant detect TUN device

### ISSUE THREAD

**Issue by sec13b** [hwdsl2/openvpn-install#38]
Error:

The TUN device is not available
You need to enable TUN before running this script

can you add the solve solution .
mkdir -p /dev/net
mknod /dev/net/tun c 10 200 
chmod 600 /dev/net/tun

thank you

**Comment by hwdsl2** [comment]
@sec13b Hello! Thank you for your suggestion. `/dev/net/tun` is usually already available on servers except for some OpenVZ VPS, in which cases it can be enabled using your server provider's control panel. Please refer to related issues https://github.com/Nyr/openvpn-install/issues/560 and https://github.com/Nyr/openvpn-install/issues/459.
