### ISSUE TITLE
dh.pem template makes it easier; but has security concerns

### ISSUE THREAD

**Issue by Hawaiideveloper** [hwdsl2/openvpn-install#41]
see more details here:

https://github.com/Hawaiideveloper/openvpn-Server-install/issues/1

**Comment by hwdsl2** [comment]
@Hawaiideveloper Hello! Thank you for bringing up this issue. These predefined DH groups are the "official" ones from RFC7919, not generated by me. Please refer to [this upstream discussion](https://github.com/Nyr/openvpn-install/commit/c90989a#commitcomment-30987566).
