### ISSUE TITLE
能否增加说明安装后怎样启动vpn

### ISSUE THREAD

**Issue by ericosmic** [hwdsl2/openvpn-install#44]
安装openvpn后，怎样导入配置文件启动vpn呢？  文档中没有相关信息，能否给出一个更详细的说明
我用openvpn --config openvpn.ovpn 启动，但是依然無法上网，能否告知原因。
![Screenshot from 2024-05-15 16-06-59](https://github.com/hwdsl2/openvpn-install/assets/35327931/638d29f0-5ede-4a87-b21a-258733346282)

**Comment by hwdsl2** [comment]
@ericosmic 你好！VPN 服务器上的 OpenVPN 服务在运行脚本安装后会自动启动并运行。如果你的用例是关于在 Linux 上的 OpenVPN 客户端导入配置文件并连接，目前文档没有说明。请参阅网络上有关 Linux 上的 OpenVPN 客户端安装配置的教程。
