### ISSUE TITLE
在阿里云 ecs  Alibaba Cloud Linux 3.2104 LTS 64位  上无法使用

### ISSUE THREAD

**Issue by freshgeek** [hwdsl2/openvpn-install#45]
os ： Alibaba Cloud Linux 3.2104 LTS 64位 快速启动版更换 

uname -a ： 
Linux iZt4nef040v39l9uiekyt5Z 5.10.134-15.al8.x86_64 #1 SMP Thu Jul 20 00:44:04 CST 2023 x86_64 x86_64 x86_64 GNU/Linux

复现步骤：
```
wget -O openvpn.sh https://get.vpnsetup.net/ovpn
sudo bash openvpn.sh --auto
Error: CentOS 7 or higher is required to use this installer.
This version of CentOS is too old and unsupported.
```

**Comment by hwdsl2** [comment]
@freshgeek 你好！目前本项目不支持 Alibaba Cloud Linux 系统。受支持的系统请参见自述文件。
