### ISSUE TITLE
OpenVpn connected but uploading/downloading speed in Bytes

### ISSUE THREAD

**Issue by ahxan07** [hwdsl2/openvpn-install#46]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/openvpn-install/blob/master/README.md)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/openvpn-install/blob/master/docs/clients.md)
- [x] I searched existing [Issues](https://github.com/hwdsl2/openvpn-install/issues?q=is%3Aissue)
- [ ] This bug is about the VPN setup script, and not OpenVPN itself

**Describe the issue**

I have deployed the openVpn following your steps.
```
wget -O openvpn.sh https://get.vpnsetup.net/ovpn
sudo bash openvpn.sh --auto
```

After that I have copied the .ovpn file and import it in openvpn app. Vpn is connected but internet is not working.
I am using macOS Sonoma

**To Reproduce**

1. ...
2. ...

**Expected behavior**

**Logs**
Add error logs to help explain the problem, if applicable.

**Server (please complete the following information)**
- OS: ubuntu 20
- Hosting provider: AWS EC2

**Client (please complete the following information)**
- Device: Macbook Pro
- OS: macOS Sonoma

**Additional context**
Plus I have deployed ipsec on same server using your script.
And Wireguard is also running on same server. (Previously configured using another script)

**Comment by hwdsl2** [comment]
@ahxan07 Hello! For your use case, if the VPN connects successfully but uploading/downloading is very slow, this is generally an issue with the network connection between your VPN client and VPN server. For example, some countries block VPN traffic or interfere with the connection. For these use cases, you may want to try other solutions such as Shadowsocks.

**Comment by ahxan07** [comment]
No, But I had previously installed openVpn using Aws marketplace. And It was working fine.
I was thinking there might be the issue with some network related thing.

Extra question: There is no issue if I deploy all vpn protocols(openVpn, wireguard, ipsec/ikev2) on same server. right?
