### ISSUE TITLE
是否可以提供支持Amazon Linux 2023的安装脚本

### ISSUE THREAD

**Issue by LiJun990105** [hwdsl2/openvpn-install#47]
**任务列表**

- [ ] 我搜索了已有的 [Issues](https://github.com/hwdsl2/openvpn-install/issues?q=is%3Aissue)，没有找到类似的改进建议
- [ ] 这个改进建议是关于 VPN 安装脚本，而不是 OpenVPN 本身
- [ ] 我已阅读 [自述文件](https://github.com/hwdsl2/openvpn-install/blob/master/README-zh.md)
- [ ] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/openvpn-install/blob/master/docs/clients-zh.md)

**描述改进建议**
使用清楚简明的语言描述你的改进建议。

**你的改进建议与遇到的问题有关吗？请描述。**
（如果适用）清楚，简洁地说明问题所在。

**其它信息**
添加关于该改进建议的其它信息。

**Comment by hwdsl2** [comment]
@LiJun990105 你好！目前本项目还没有支持 Amazon Linux 2023 的计划。但你可以自己尝试修改脚本实现。
