### ISSUE TITLE
Update easy-rsa in existing install

### ISSUE THREAD

**Issue by jcastilloalonso** [hwdsl2/openvpn-install#48]
**Checklist**

- [X] I read the [README](https://github.com/hwdsl2/openvpn-install/blob/master/README.md)
- [X] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/openvpn-install/blob/master/docs/clients.md)
- [X] I searched existing [Issues](https://github.com/hwdsl2/openvpn-install/issues?q=is%3Aissue)
- [X] This bug is about the VPN setup script, and not OpenVPN itself

**Describe the issue**
Noticed an update to script for new easy-rsa version, yet I'm not sure how to update it without breaking current clients.
Is there any guide or script (like ipsec vpnup.sh) to upgrade?

Thanks a lot for your easy to use scripts!

**To Reproduce**

1. ... N/A
2. ...

**Expected behavior**
Either current openvpn.sh script to detect version and offer to upgrade, or a separate script to perform the check and upgrade as needed.

**Logs**
N/A

**Server (please complete the following information)**
N/A

**Client (please complete the following information)**
N/A

**Additional context**
N/A

**Comment by hwdsl2** [comment]
@jcastilloalonso Hello! Currently, the VPN script in this project does not support upgrading easy-rsa to a newer version. If the installed easy-rsa version on your server works fine for you, you can generally keep using it without upgrading.

On the other hand, if your use case requires a newer easy-rsa version (refer to [easy-rsa releases](https://github.com/OpenVPN/easy-rsa/releases)), you may be able to manually upgrade it by extracting the newer version into the `/etc/openvpn/server/easy-rsa/` folder and setting appropriate permissions. Note that this process has not been tested, try it at your own risk. Before upgrading, make sure that you make a backup of the entire `/etc/openvpn/server/easy-rsa/` folder in case something goes wrong.

References:
https://github.com/hwdsl2/openvpn-install/blob/fafb5b9e49cce045cf534fb6a7a5de61cdb1e5b3/openvpn-install.sh#L648-L656
https://github.com/OpenVPN/easy-rsa/blob/master/doc/EasyRSA-Upgrade-Notes.md
https://community.openvpn.net/openvpn/wiki/easyrsa-upgrade#ersa-up33
