### ISSUE TITLE
Unable to communicate between clients

### ISSUE THREAD

**Issue by ProgrammerXiaoQin** [hwdsl2/openvpn-install#49]
Hello, I have successfully installed and created two clients on my Centos7. However, communication between the two clients is not working properly. Is this normal

**Comment by hwdsl2** [comment]
@ProgrammerXiaoQin Hello! By default, client-to-client traffic is allowed in the firewall rules created by the script in this project, please use the clients' internal IP addresses (10.8.0.0/24 subnet) to communicate with each other. To view which IP is assigned to a client, check the connection properties on the OpenVPN client. Note that client-to-client traffic may be blocked by the firewalls on your OpenVPN clients themselves.

**Comment by ProgrammerXiaoQin** [comment]
Thank you for your reply. I have checked my network situation and it should be no problem. I successfully resolved the issue by restarting the OpenVPN service (systemctl restart openvpn-server@server.service ）
