### ISSUE TITLE
是否有在线数量的限制

### ISSUE THREAD

**Issue by haouvw** [hwdsl2/openvpn-install#50]
看官方的文档，好像只能同时在线2-3人吗？ 使用这个脚本搭建，不知是否有此限制？

另外如何保持最新的openvpn server的版本呢？

感谢！

**Comment by hwdsl2** [comment]
@haouvw 你好！本项目使用 OpenVPN 的 community 版本，一般来说是直接从你的 Linux 发行版的官方软件仓库安装，没有预设的对于同时连接数量的限制。对于更新 OpenVPN 版本，一般只需要使用你的服务器的 Linux 发行版的软件管理程序即可，比如 Ubuntu/Debian 上的 apt。具体软件包名称请参见脚本。
