### ISSUE TITLE
可以添加 warp 的支持吗

### ISSUE THREAD

**Issue by 2556227850** [hwdsl2/openvpn-install#52]
**任务列表**

- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/openvpn-install/issues?q=is%3Aissue)，没有找到类似的改进建议
- [x] 这个改进建议是关于 VPN 安装脚本，而不是 OpenVPN 本身
- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/openvpn-install/blob/master/README-zh.md)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/openvpn-install/blob/master/docs/clients-zh.md)

**描述改进建议**
可以添加 warp 的支持吗

**Comment by hwdsl2** [comment]
@2556227850 你好！该功能超出了本项目的范围，目前没有计划添加。
