### ISSUE TITLE
Add block/allow for spesific website

### ISSUE THREAD

**Issue by taehyongsuzuki** [hwdsl2/openvpn-install#54]
its possible to add some feature Add block/allow for spesific website?

**Comment by hwdsl2** [comment]
@taehyongsuzuki Hello! This feature is outside the scope of this project and not supported.

**Comment by taehyongsuzuki** [comment]
are there any tips for doing that?

Pada Min, 11 Agu 2024 pukul 00.15 Lin Song ***@***.***>
menulis:
