### ISSUE TITLE
Support installation for both UDP and TCP protocols simultaneously

### ISSUE THREAD

**Issue by ezverev** [hwdsl2/openvpn-install#55]
**Checklist**

- [+] I searched existing [Issues](https://github.com/hwdsl2/openvpn-install/issues?q=is%3Aissue), and did not find a similar enhancement request
- [+] This enhancement request is about the VPN setup script, and not OpenVPN itself
- [+] I read the [README](https://github.com/hwdsl2/openvpn-install/blob/master/README.md)
- [+] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/openvpn-install/blob/master/docs/clients.md)

**Describe the enhancement request**
You can run multiple instances of OpenVPN daemon and thus support both UDP and TCP on a single machine.

**Is your enhancement request related to a problem? Please describe.**
-

**Additional context**
-

**Comment by hwdsl2** [comment]
@ezverev Hello! Thank you for your suggestion. Currently, this feature is not planned. The script installs a single instance of the OpenVPN daemon, so you'll need to select between UDP and TCP for the OpenVPN protocol.
