### ISSUE TITLE
添加卸载脚本

### ISSUE THREAD

**Issue by Zhou-Shilin** [hwdsl2/openvpn-install#56]
**任务列表**

- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/openvpn-install/issues?q=is%3Aissue)，没有找到类似的改进建议
- [x] 这个改进建议是关于 VPN 安装脚本，而不是 OpenVPN 本身
- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/openvpn-install/blob/master/README-zh.md)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/openvpn-install/blob/master/docs/clients-zh.md)

**描述改进建议**
添加卸载脚本。

**你的改进建议与遇到的问题有关吗？请描述。**
无。

**其它信息**
无。

**Comment by hwdsl2** [comment]
@Zhou-Shilin 你好！要卸载 OpenVPN，请运行脚本并选择适当的选项：
```
sudo bash openvpn.sh
```
