### ISSUE TITLE
openvpn的配置文件在哪里下载和查看

### ISSUE THREAD

**Issue by zhiquanchi** [hwdsl2/openvpn-install#57]
我知道这是一个很愚蠢的问题，但我是一个初学者，没有在文档和帮助找到对应的信息

**Comment by hwdsl2** [comment]
@zhiquanchi 你好！在成功运行脚本安装 OpenVPN 后，会显示生成的客户端配置文件的路径和名称，例如 `/root/client.ovpn`。要添加 VPN 连接，首先将生成的 .ovpn 文件安全地传送到你的设备，然后打开 OpenVPN 应用程序并导入 VPN 配置文件。请参见[配置 OpenVPN 客户端](https://github.com/hwdsl2/openvpn-install/blob/master/docs/clients-zh.md)。
