### ISSUE TITLE
linux mint not supported

### ISSUE THREAD

**Issue by DjinnDjab** [hwdsl2/openvpn-install#6]
**Checklist**

- [x] I read the [README](https://github.com/hwdsl2/openvpn-install/blob/master/README.md)
- [x] I followed instructions to [configure VPN clients](https://github.com/hwdsl2/openvpn-install/blob/master/docs/clients.md)
- [x] I searched existing [Issues](https://github.com/hwdsl2/openvpn-install/issues?q=is%3Aissue)
- [x] This bug is about the VPN setup script, and not OpenVPN itself

**Describe the issue**
running script on linux mint 21.1 results in:

Error: Ubuntu 18.04 or higher is required to use this installer.
This version of Ubuntu is too old and unsupported.

**To Reproduce**

1. run script as instructed on a linux 21.1 machine

**Expected behavior**
successful execution of scripting

**Logs**

Error: Ubuntu 18.04 or higher is required to use this installer.
This version of Ubuntu is too old and unsupported.

**Server (please complete the following information)**
- OS: Linux Mint 21.1
- Hosting provider (if applicable): N/A

**Client (please complete the following information)**
- Device: N/A
- OS: N/A

**Additional context**
Linux Mint 21 is based on Ubuntu 22.04 which satisfies the minimum version requirements.

**Comment by hwdsl2** [comment]
@DjinnDjab Hello! Thank you for reporting this issue. As Linux Mint is not a commonly used server distribution, this project does not currently support it. However, for your use case, you can manually modify the OpenVPN script to remove the OS check. This script has not been tested on Linux Mint.
