### ISSUE TITLE
download easy rsa  get a error.

### ISSUE THREAD

**Issue by ffashion** [hwdsl2/openvpn-install#61]
**问题描述**
download easy rsa get a error in ubuntu 22.02 
**重现步骤**
重现该 bug 的步骤：

1. sudo bash openvpn.sh --auto

**期待的正确结果**
corrent to install. 
**日志**
Installing OpenVPN, please wait...
+ apt-get -yqq update
+ apt-get -yqq --no-install-recommends install openvpn
+ apt-get -yqq install openssl ca-certificates
gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: Failed to download EasyRSA from https://github.com/OpenVPN/easy-rsa/releases/download/v3.2.1/EasyRSA-3.2.1.tgz.

**服务器信息（请填写以下信息）**
- 操作系统: ubuntu 22.04

some software version: 
tar (GNU tar) 1.34
Copyright (C) 2021 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by John Gilmore and Jay Fenlason.

**Comment by hwdsl2** [comment]
@ffashion Hello! I could not reproduce this error, the download URL seems to work fine. This may be a temporary issue (try again to see if it works), or your server may be blocking access to GitHub.
