### ISSUE TITLE
 Single Client Connection

### ISSUE THREAD

**Issue by MajdevInc** [hwdsl2/openvpn-install#64]
Hello,
I have reviewed your project. I appreciate that you have simplified this setup. However, the issue is that with the config file I created, only one user can connect at a time. I don't believe this is related to your work; it seems to be how the OpenVPN software operates. How can we enable multiple users to connect simultaneously with a single config file?

**Comment by hwdsl2** [comment]
@MajdevInc Hello! For your use case, to allow multiple users to connect simultaneously with a single config file, you can set the `duplicate-cn` directive in the server configuration file `/etc/openvpn/server/server.conf` and restart the service using `sudo systemctl restart openvpn-server@server.service` to apply the changes.

However, it is generally recommended to create a unique configuration for each user by running the installation script again and selecting the appropriate option.
