### ISSUE TITLE
增加openvpn开启认证模式

### ISSUE THREAD

**Issue by nilongpeng** [hwdsl2/openvpn-install#65]
**任务列表**

- [ ✅] 我搜索了已有的 [Issues](https://github.com/hwdsl2/openvpn-install/issues?q=is%3Aissue)，没有找到类似的改进建议
- [ ✅] 这个改进建议是关于 VPN 安装脚本，而不是 OpenVPN 本身
- [ 对] 我已阅读 [自述文件](https://github.com/hwdsl2/openvpn-install/blob/master/README-zh.md)
- [ 对] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/openvpn-install/blob/master/docs/clients-zh.md)

**描述改进建议**
建议增加openvpn开启认证模式，用户需要输入用户名和密码方可访问相关网络，

**Comment by hwdsl2** [comment]
@nilongpeng 你好！感谢你的建议。本项目目前没有计划添加该功能，但你可以自行修改安装脚本来尝试实现你的用例。
