### ISSUE TITLE
增加限速功能

### ISSUE THREAD

**Issue by saymyname77** [hwdsl2/openvpn-install#66]
**任务列表**

- [* ] 我搜索了已有的 [Issues](https://github.com/hwdsl2/openvpn-install/issues?q=is%3Aissue)，没有找到类似的改进建议
- [* ] 这个改进建议是关于 VPN 安装脚本，而不是 OpenVPN 本身
- [* ] 我已阅读 [自述文件](https://github.com/hwdsl2/openvpn-install/blob/master/README-zh.md)
- [* ] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/openvpn-install/blob/master/docs/clients-zh.md)

**描述改进建议**
增加限速功能。

**Comment by hwdsl2** [comment]
@saymyname77 你好！感谢你的建议。目前本项目没有计划添加该功能。
