### ISSUE TITLE
安装后无法启动openvpn

### ISSUE THREAD

**Issue by Hyominnnn** [hwdsl2/openvpn-install#67]
**任务列表**

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/openvpn-install/blob/master/README-zh.md)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/openvpn-install/blob/master/docs/clients-zh.md)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/openvpn-install/issues?q=is%3Aissue)
- [x] 这个 bug 是关于 VPN 安装脚本，而不是 OpenVPN 本身

**问题描述**
安装后无法启动openvpn，查看openvpn的状态发现指向的/etc/openvpn/server.conf而不是/etc/openvpn/server/server.conf

**重现步骤**
重现该 bug 的步骤：

1. ...
2. ...

**期待的正确结果**
正常启动

**日志**
![WX20241205-164641@2x](https://github.com/user-attachments/assets/c84989af-302e-4050-aa8d-c89b859e150f)

**服务器信息（请填写以下信息）**
- 操作系统: [比如 Debian 11]
ubuntu 22.04
- 服务提供商（如果适用）: [比如 GCP, AWS]

**客户端信息（请填写以下信息）**
- 设备: [比如 iPhone 12]
- 操作系统: [比如 iOS 15]

**其它信息**
添加关于该 bug 的其它信息。

**Comment by hwdsl2** [comment]
@Hyominnnn 你好！脚本默认使用 `openvpn-server@server.service` 而不是 `openvpn@server.service`。请参见：
https://github.com/hwdsl2/openvpn-install/blob/4b5ccc7714c72a013421bc81e76d673c816186cd/openvpn-install.sh#L1149

所以正确的命令应该是 `systemctl status openvpn-server@server.service`。
