### ISSUE TITLE
希望支持udp6

### ISSUE THREAD

**Issue by JazzDKnight** [hwdsl2/openvpn-install#7]
**任务列表**

- [1] 我搜索了已有的 [Issues](https://github.com/hwdsl2/openvpn-install/issues?q=is%3Aissue)，没有找到类似的改进建议
- [1] 这个改进建议是关于 VPN 安装脚本，而不是 OpenVPN 本身
- [1] 我已阅读 [自述文件](https://github.com/hwdsl2/openvpn-install/blob/master/README-zh.md)
- [1] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/openvpn-install/blob/master/docs/clients-zh.md)

**描述改进建议**
希望在配置脚本过程中可以配置纯IPv6的连接

**你的改进建议与遇到的问题有关吗？请描述。**
校园网对于IPv6流量免流，所以我有proto使用udp6的需求。我详细阅读了配置过程，脚本缺失了这方面的配置。

**Comment by hwdsl2** [comment]
@JazzDKnight 你好！感谢你的建议。目前本项目没有支持纯IPv6 连接的计划。

你可以在安装后尝试将服务器上的OpenVPN配置文件和生成的客户端配置文件中的服务器地址都改成你的服务器的IPv6地址，然后重启服务器，看看能否连接。
