### ISSUE TITLE
ipv6地址泄露

### ISSUE THREAD

**Issue by deemo021211** [hwdsl2/openvpn-install#8]
**任务列表**

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/openvpn-install/blob/master/README-zh.md)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/openvpn-install/blob/master/docs/clients-zh.md)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/openvpn-install/issues?q=is%3Aissue)
- [x] 这个 bug 是关于 VPN 安装脚本，而不是 OpenVPN 本身

**问题描述**
使用清楚简明的语言描述这个 bug。

**重现步骤**
重现该 bug 的步骤：

1. ...我的客户端网络有ipv4+ipv6地址
2. ...我的服务器只有ipv4地址却没有ipv6地址
3. ..我的服务器使用该脚本安装了openvpn
4. ..我的客户端使用服务器生成的配置文件连接到vpn
5. ...访问ipv6地址的检测网站，将会显示我的真实ipv6地址

**期待的正确结果**
简要地描述你期望的正确结果。

**日志**
添加错误日志以帮助解释该问题（如果适用）。

**服务器信息（请填写以下信息）**
- 操作系统: [比如 Debian 11]
- 服务提供商（如果适用）: [比如 GCP, AWS]

**客户端信息（请填写以下信息）**
- 设备: [比如 iPhone 12]
- 操作系统: [比如 iOS 15]

**其它信息**
添加关于该 bug 的其它信息。

**Comment by hwdsl2** [comment]
@deemo021211 你好！对于此用例，因为你的服务器只有 IPv4 地址而没有 IPv6 地址，脚本添加的 IP6Tables 规则无法将你的客户端的 IPv6 流量通过服务器转发。该情况下 IPv6 流量不经过服务器是正常的。要解决此问题，请换用有 IPv4 + IPv6 地址的服务器。
