### ISSUE TITLE
不支持连接IPV6地址的服务器

### ISSUE THREAD

**Issue by deemo021211** [hwdsl2/openvpn-install#9]
**任务列表**

- [x] 我已阅读 [自述文件](https://github.com/hwdsl2/openvpn-install/blob/master/README-zh.md)
- [x] 我已按照说明 [配置 VPN 客户端](https://github.com/hwdsl2/openvpn-install/blob/master/docs/clients-zh.md)
- [x] 我搜索了已有的 [Issues](https://github.com/hwdsl2/openvpn-install/issues?q=is%3Aissue)
- [x] 这个 bug 是关于 VPN 安装脚本，而不是 OpenVPN 本身

**问题描述**
使用清楚简明的语言描述这个 bug。

**重现步骤**
重现该 bug 的步骤：

1. ...服务器有ipv4+ipv6网络，以亚马逊为例
2. ...通过该脚本安装并生成配置文件
3. ...修改配置文件中的参数为udp6，并且地址改成对应的ipv6地址
4. ...客户端导入配置文件，点击连接会显示一直等待服务器响应，无法连接，wireguard脚本没有这个问题

**期待的正确结果**
简要地描述你期望的正确结果。

**日志**
添加错误日志以帮助解释该问题（如果适用）。

**服务器信息（请填写以下信息）**
- 操作系统: [比如 Debian 11]
- 服务提供商（如果适用）: [比如 GCP, AWS]

**客户端信息（请填写以下信息）**
- 设备: [比如 iPhone 12]
- 操作系统: [比如 iOS 15]

**其它信息**
添加关于该 bug 的其它信息。

**Comment by hwdsl2** [comment]
@deemo021211 你好！本项目目前不支持使用服务器的 IPv6 地址连接，请使用其 IPv4 地址。你可以尝试修改 `/etc/openvpn/server/server.conf` 中的地址为服务器的 IPv6 地址，然后重启服务器，但此方法未测试过。
